In [14]:
import numpy as np
import matplotlib.pyplot as plt
from utils import *
import copy
import math

<a name="2"></a>
## 2 - Logistic Regression

In this part of the exercise, you will build a logistic regression model to predict whether a student gets admitted into a university.

<a name="2.1"></a>
### 2.1 Problem Statement

Suppose that you are the administrator of a university department and you want to determine each applicant’s chance of admission based on their results on two exams. 
* You have historical data from previous applicants that you can use as a training set for logistic regression. 
* For each training example, you have the applicant’s scores on two exams and the admissions decision. 
* Your task is to build a classification model that estimates an applicant’s probability of admission based on the scores from those two exams. 

<a name="2.2"></a>
### 2.2 Loading and visualizing the data

You will start by loading the dataset for this task. 
- The `load_dataset()` function shown below loads the data into variables `X_train` and `y_train`
  - `X_train` contains exam scores on two exams for a student
  - `y_train` is the admission decision 
      - `y_train = 1` if the student was admitted 
      - `y_train = 0` if the student was not admitted 
  - Both `X_train` and `y_train` are numpy arrays.


In [15]:
x_train = [34.62365962, 78.02469282, 30.28671077, 43.89499752, 35.84740877,
       72.90219803, 60.18259939, 86.3085521 , 79.03273605, 75.34437644,
       45.08327748, 56.31637178, 61.10666454, 96.51142588, 75.02474557,
       46.55401354, 76.0987867 , 87.42056972, 84.43281996, 43.53339331,
       95.86155507, 38.22527806, 75.01365839, 30.60326323, 82.30705337,
       76.4819633 , 69.36458876, 97.71869196, 39.53833914, 76.03681085,
       53.97105215, 89.20735014, 69.07014406, 52.74046973, 67.94685548,
       46.67857411, 70.66150955, 92.92713789, 76.97878373, 47.57596365,
       67.37202755, 42.83843832, 89.67677575, 65.79936593, 50.53478829,
       48.85581153, 34.21206098, 44.2095286 , 77.92409145, 68.97235999,
       62.27101367, 69.95445795, 80.19018075, 44.82162893, 93.1143888 ,
       38.80067034, 61.83020602, 50.25610789, 38.7858038 , 64.99568096,
       61.37928945, 72.80788731, 85.40451939, 57.05198398, 52.10797973,
       63.12762377, 52.04540477, 69.43286012, 40.23689374, 71.16774802,
       54.63510555, 52.21388588, 33.91550011, 98.86943574, 64.17698887,
       80.90806059, 74.78925296, 41.57341523, 34.18364003, 75.23772034,
       83.90239366, 56.30804622, 51.54772027, 46.85629026, 94.44336777,
       65.56892161, 82.36875376, 40.61825516, 51.04775177, 45.82270146,
       62.22267576, 52.06099195, 77.19303493, 70.4582    , 97.77159928,
       86.72782233, 62.0730638 , 96.76882412, 91.5649745 , 88.69629255,
       79.94481794, 74.16311935, 99.27252693, 60.999031  , 90.54671411,
       43.39060181, 34.52451385, 60.39634246, 50.28649612, 49.80453881,
       49.58667722, 59.80895099, 97.64563396, 68.86157272, 32.57720017,
       95.59854761, 74.24869137, 69.82457123, 71.79646206, 78.45356225,
       75.39561147, 85.75993667, 35.28611282, 47.02051395, 56.2538175 ,
       39.26147251, 30.05882245, 49.59297387, 44.66826172, 66.45008615,
       66.56089447, 41.09209808, 40.45755098, 97.53518549, 49.07256322,
       51.88321182, 80.27957401, 92.11606081, 66.74671857, 60.99139403,
       32.72283304, 43.30717306, 64.03932042, 78.03168802, 72.34649423,
       96.22759297, 60.45788574, 73.0949981 , 58.84095622, 75.85844831,
       99.8278578 , 72.36925193, 47.26426911, 88.475865  , 50.4581598 ,
       75.80985953, 60.45555629, 42.50840944, 82.22666158, 42.71987854,
       88.91389642, 69.8037889 , 94.83450672, 45.6943068 , 67.31925747,
       66.58935318, 57.23870632, 59.51428198, 80.366756  , 90.9601479 ,
       68.46852179, 85.5943071 , 42.07545454, 78.844786  , 75.47770201,
       90.424539  , 78.63542435, 96.64742717, 52.34800399, 60.76950526,
       94.09433113, 77.15910509, 90.44855097, 87.50879176, 55.48216114,
       35.57070347, 74.49269242, 84.84513685, 89.84580671, 45.35828361,
       83.48916274, 48.3802858 , 42.26170081, 87.10385094, 99.31500881,
       68.77540947, 55.34001756, 64.93193801, 74.775893  , 89.5298129]
X_train = np.array(x_train).reshape((100,2))
X_train.shape

(100, 2)

In [16]:
y_train = np.array([0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1.,
    0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1.,
    0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1.,
    1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
    1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1.,
    1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.])
y_train.shape

(100,)

In [17]:
print("First five elements in X_train are:\n", X_train[:5])
print("Type of X_train:",type(X_train))

First five elements in X_train are:
 [[34.62365962 78.02469282]
 [30.28671077 43.89499752]
 [35.84740877 72.90219803]
 [60.18259939 86.3085521 ]
 [79.03273605 75.34437644]]
Type of X_train: <class 'numpy.ndarray'>


In [18]:
print("First five elements in y_train are:\n", y_train[:5])
print("Type of y_train:",type(y_train))

First five elements in y_train are:
 [0. 0. 0. 1. 1.]
Type of y_train: <class 'numpy.ndarray'>


In [19]:
print ('The shape of X_train is: ' + str(X_train.shape))
print ('The shape of y_train is: ' + str(y_train.shape))
print ('We have m = %d training examples' % (len(y_train)))

The shape of X_train is: (100, 2)
The shape of y_train is: (100,)
We have m = 100 training examples


In [20]:
def sigmoid(z):
    
    g = 1 / (1 + np.exp(-z))

    return g


In [21]:
print ("sigmoid(0) = " + str(sigmoid(0)))

sigmoid(0) = 0.5


In [22]:
print ("sigmoid([ -1, 0, 1, 2]) = " + str(sigmoid(np.array([-1, 0, 1, 2]))))

sigmoid([ -1, 0, 1, 2]) = [0.26894142 0.5        0.73105858 0.88079708]


In [32]:
def compute_cost(X, y, w, b, lambda_= 1):
    m, n = X.shape
    
    cost = 0
    
    for i in range(m) :
        z = np.dot(X[i],w) + b
        f_wb = sigmoid(z)
        cost += - y[i] * np.log(f_wb) - (1 - y[i]) * np.log(1 - f_wb)
    total_cost = cost / m    
    
    return total_cost

In [33]:
m, n = X_train.shape

# Compute and display cost with w initialized to zeroes
initial_w = np.zeros(n)
initial_b = 0.
cost = compute_cost(X_train, y_train, initial_w, initial_b)
print('Cost at initial w (zeros): {:.3f}'.format(cost))

Cost at initial w (zeros): 0.693


In [34]:
test_w = np.array([0.2, 0.2])
test_b = -24.
cost = compute_cost(X_train, y_train, test_w, test_b)

print('Cost at test w,b: {:.3f}'.format(cost))

Cost at test w,b: 0.218


In [37]:
def compute_gradient(x,y,w,b) :
    
    m,n = x.shape
    w_d = np.zeros(w.shape)
    b_d = 0.
    
    for i in range(m) :
        
        f_wb = sigmoid(np.dot(x[i],w) + b)
        err = f_wb - y[i]
        
        for j in range(n) :
        
            w_d = w_d + err *x[i,j]
        
        b_d = b_d + err
        
    w_d = w_d / m
    b_d = b_d / m
    
    return w_d , b_d

In [40]:
# Compute and display gradient with w initialized to zeroes
initial_w = np.zeros(n)
initial_b = 0.

dj_db, dj_dw = compute_gradient(X_train, y_train, initial_w, initial_b)
print(f'dj_dw at initial w (zeros):{dj_db}' )
print(f'dj_db at initial b (zeros):{dj_dw.tolist()}' )


dj_dw at initial w (zeros):[-23.27205879 -23.27205879]
dj_db at initial b (zeros):-0.1


In [41]:
# Compute and display cost and gradient with non-zero w
test_w = np.array([ 0.2, -0.5])
test_b = -24
dj_db, dj_dw  = compute_gradient(X_train, y_train, test_w, test_b)

print('dj_db at test_w:', dj_db)
print('dj_dw at test_w:', dj_dw.tolist())

dj_db at test_w: [-89.20519487 -89.20519487]
dj_dw at test_w: -0.5999999999991071


In [42]:
def gradient_descent(x, y, w_in, b_in, compute_cost, compute_gradient, alpha, num_iters, lambda_): 
    
    m = len(x)
    
    j_history = []
    w_history = []
    
    for i in range(num_iters) :
        
        w_d , b_d = compute_gradient(x,y,w_in,b_in)
        
        w_in = w_in - alpha * w_d 
        b_in = b_in - alpha * b_d 
        
        if i<100000:      # prevent resource exhaustion 
            cost =  compute_cost(x, y, w_in, b_in)
            j_history.append(cost)
        
        if i% math.ceil(num_iters/10) == 0 or i == (num_iters-1):
            w_history.append(w_in)
            print(f"Iteration {i:4}: Cost {float(j_history[-1]):8.2f}   ")        
            
    return w_in , b_in ,j_history ,w_history            

In [60]:
np.random.seed(1)
intial_w = 0.01 * (np.random.rand(2).reshape(-1,1) - 0.5)
initial_b = -8


# Some gradient descent settings
iterations = 10000
alpha = 0.001
# iter = []
# for i in range(iterations) :
#     iter.append(i)
w,b, J_history,w_history = gradient_descent(X_train ,y_train, initial_w, initial_b, 
                            compute_cost, compute_gradient, alpha, iterations, 0)


Iteration    0: Cost     0.75   
Iteration 1000: Cost     0.65   
Iteration 2000: Cost     0.65   
Iteration 3000: Cost     0.64   
Iteration 4000: Cost     0.64   
Iteration 5000: Cost     0.63   
Iteration 6000: Cost     0.63   
Iteration 7000: Cost     0.62   
Iteration 8000: Cost     0.62   
Iteration 9000: Cost     0.61   
Iteration 9999: Cost     0.44   


In [54]:
def predict(x,w,b) :
    
    m,n = x.shape
    
    p = np.zeros(m)
    
    for i in range(m) :
        
        z = np.dot (x[i] , w) 
        
        for j in range(n) :
            
            z += 0
        z += b
            
        f_wb = sigmoid(z)
    
        if (f_wb >= 0.5) :
            p[i] = 1
        else :
            p[i] = 0
    
    return p            

In [59]:
# Test your predict code
np.random.seed(1)
tmp_w = np.random.randn(2)
tmp_b = 0.3    
tmp_X = np.random.randn(4, 2) - 0.5
print(tmp_X)
tmp_p = predict(tmp_X, tmp_w, tmp_b)
print(f'Output of predict: shape {tmp_p.shape}, value {tmp_p}')


[[-1.02817175 -1.57296862]
 [ 0.36540763 -2.8015387 ]
 [ 1.24481176 -1.2612069 ]
 [-0.1809609  -0.74937038]]
Output of predict: shape (4,), value [0. 1. 1. 1.]
